FROM python:3.7
#ENV http_proxy http://proxy-chain.xxx.com:911/
#ENV https_proxy http://proxy-chain.xxx.com:912/
ENV PYTHONUNBUFFERED 1
RUN mkdir /src
WORKDIR /src
ADD src/api/requirements.txt /src/
RUN pip3 install -r requirements.txt
ADD . /src/ 
ADD src/api/ /src/
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]
